# Generated by Django 5.2.1 on 2025-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_id',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
    ]
